version: '3.8'

services:
  api-gateway:
    image: api-gateway:dev  
    build:
      context: .
      dockerfile: apigateway/Dockerfile  
    ports:
      - "7000:8080"  
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - app-network

  identitymicroservice:
    image: identitymicroservice:dev  
    build:
      context: .
      dockerfile: musicapp.identity.identityservice/Dockerfile 
    ports:
      - "7001:8080"  
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - app-network

  musicmicroservice:
    image: musicmicroservice:dev  
    build:
      context: .
      dockerfile: musicapp.music.musicservice/Dockerfile  
    ports:
      - "7002:8080"  
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
